### ISSUE TITLE
Relics not respecting pvp change [1.21.1]

### ISSUE THREAD

**Issue by Tenebrean** [SSKirillSS/relics#174] opened 2024-10-02 00:22 UTC
Holy Locket shoots players as a target even with global pvp turned off, Can kill them if healing taken is strong enough and ignores their armor. (modpack Allthemods 10)

Used Iron's Spell to heal myself and the healing bonus was so high a friend nearby got hit from full health to 0 and died.

**Comment by SSKirillSS** [comment] 2024-10-19 03:48
Hi. Thanks for the info. Will be _potentially_ fixed in the next update. You can reopen the issue is it will still appear for you after the update.

**Closed as completed by SSKirillSS** 2024-10-19 03:48 UTC
