### ISSUE TITLE
Passive becomes Active Ability

### ISSUE THREAD

**Issue by RobertHDPotatoes** [SSKirillSS/relics#45] opened 2021-11-07 21:16 UTC
If you equip the Arrow Quiver, then draw an arrow back in the bow and use the active ability while the bow is drawn, you will cause the passive ability (Flexible Bowstring) to turn off.

Here is a video demonstrating the bug: https://www.youtube.com/watch?v=5XNDIJLlcts

**Comment by RobertHDPotatoes** [comment] 2021-11-07 21:26
Upon further investigation, this may be intended behavior. I'm not sure, so if it is just close this issue.

**Comment by SSKirillSS** [comment] 2021-11-09 05:29
Hey. Thanks for the info. This issue caused by rude check of cooldown while searching for equipped relic: https://github.com/SSKirillSS/relics/blob/master/src/main/java/it/hurts/sskirillss/relics/utils/EntityUtils.java#L169

Will be fixed in the nearest future.

**Comment by SSKirillSS** [comment] 2022-01-05 19:15
Should be fixed now. Can be downloaded here: **[click](https://www.curseforge.com/minecraft/mc-mods/relics-mod/files/3593459)**.

**Closed by SSKirillSS** 2022-01-05 19:15 UTC
