### ISSUE TITLE
the game freeze when i use the mirror in the nether

### ISSUE THREAD

**Issue by linxcy** [SSKirillSS/relics#11] opened 2021-04-25 15:55 UTC
not only the mirror ,the spatial sign has the same problem.

**Comment by linxcy** [comment] 2021-04-25 15:59
and i found this in the debug log.

[Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.world.World.func_189509_E(World.java:151) ~[?:?]
	at net.minecraft.world.World.func_180495_p(World.java:376) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_241830_a(ServerPlayerEntity.java:706) ~[?:?]
	at net.minecraft.entity.Entity.func_241829_a(Entity.java:2179) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_241829_a(ServerPlayerEntity.java:612) ~[?:?]
	at net.minecraftforge.common.util.ITeleporter.getPortalInfo(ITeleporter.java:84) ~[forge:?]
	at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:645) ~[?:?]
	at net.minecraft.entity.Entity.func_241206_a_(Entity.java:2120) ~[?:?]
	at it.hurts.sskirillss.relics.utils.EntityUtils.teleportWithMount(EntityUtils.java:31) ~[relics:0.1.10.2]
	at it.hurts.sskirillss.relics.items.relics.MagicMirrorItem.func_77659_a(MagicMirrorItem.java:52) ~[relics:0.1.10.2]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

**Comment by linxcy** [comment] 2021-04-25 16:03
[debug-1.log](https://github.com/SSKirillSS/relics/files/6372347/debug-1.log)
here is the debug log.

**Comment by SSKirillSS** [comment] 2021-04-26 10:03
@linxcy, can you try to reproduce issue with this build of mod?
Link: https://www.mediafire.com/file/gmouhiyrxzy5z22/relics-0.1.10.2.jar/file

Also, would be better if you join mod Discord for discussing this issue if a new build doesn't fix it.

**Comment by linxcy** [comment] 2021-04-26 14:30
Ok, I'll try.

**Comment by linxcy** [comment] 2021-04-26 16:56
[Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.world.World.func_189509_E(World.java:151) ~[?:?]
	at net.minecraft.world.World.func_180495_p(World.java:376) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_241830_a(ServerPlayerEntity.java:706) ~[?:?]
	at net.minecraft.entity.Entity.func_241829_a(Entity.java:2179) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_241829_a(ServerPlayerEntity.java:612) ~[?:?]
	at net.minecraftforge.common.util.ITeleporter.getPortalInfo(ITeleporter.java:84) ~[forge:?]
	at net.minecraft.entity.player.ServerPlayerEntity.changeDimension(ServerPlayerEntity.java:645) ~[?:?]
	at net.minecraft.entity.Entity.func_241206_a_(Entity.java:2120) ~[?:?]
	at it.hurts.sskirillss.relics.utils.EntityUtils.teleportWithMount(EntityUtils.java:31) ~[relics:0.1.10.2]
	at it.hurts.sskirillss.relics.items.relics.SpatialSignItem.teleportPlayer(SpatialSignItem.java:98) ~[relics:0.1.10.2]
	at it.hurts.sskirillss.relics.items.relics.SpatialSignItem.func_77659_a(SpatialSignItem.java:66) ~[relics:0.1.10.2]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:287) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147346_a(ServerPlayNetHandler.java:982) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:31) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemPacket.func_148833_a(SourceFile:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

still the same problem

**Comment by SSKirillSS** [comment] 2021-04-26 16:57
For unknown reason I can't reproduce your issue. Can you tell me more about how you did it? Or maybe capture a video or something.

**Comment by linxcy** [comment] 2021-04-26 17:15
it is hard to say how it happened.
i just exploring the nether normally.
when i want to go back to the overword i use the mirror but after doing that the game freeze at the loading screen.
althought the game freeze at the loading screen, i still can hear the soud of the animal around me.

**Comment by SSKirillSS** [comment] 2021-04-26 17:27
Are you playing on the server, or this is a singleplayer game? Also, can you check it in the clean new world with only Relics and Curios installed? Cuz as I checked in singleplayer world with only Relics mod installed, mirror works fine and teleports between dimensions without errors.

**Comment by linxcy** [comment] 2021-04-26 17:35
just singleplayer game not a server.
i will check the bug later.

**Comment by linxcy** [comment] 2021-04-27 17:10
This problem may not occur in the world created in the new version, but it still exists in the world created in the old version.
If I meet the same problem in the new world, I will report it again.

**Comment by Jackiecrazy** [comment] 2021-05-04 10:08
This still happens on Relics 0.1.13 on my side. I cannot teleport home from the twilight forest on a new world.

**Comment by SSKirillSS** [comment] 2021-05-08 14:34
Should be fixed in https://github.com/SSKirillSS/relics/commit/3ad8055907ab222b2f26b756e91ad4f98aca5da3

**Closed** 2021-05-08 14:34 UTC
Labels: bug, can't reproduce
