### ISSUE TITLE
[1.21 NeoForge] Ender Hand in right hand crashes game 

### ISSUE THREAD

**Issue by ptlthg** [SSKirillSS/relics#151] opened 2024-07-07 01:43 UTC
**Describe the bug**
Equipping an ender hand relic in your left-hand slot crashes the game. We were able to reproduce this 3 times in a row. It seems to work fine on a player's right hand. I had to manually edit the player.dat file to remove the hand from their inventory in order to prevent them from crashing on login.
 
Crash log: https://mclo.gs/4ARBFCm

**To Reproduce**
1. Equip Ender Hand relic on your left hand
2. Game crashes

**System:**
- Relics Version: 0.7.1.4 (NeoForge)
- OS: Windows 10
- Minecraft Version: 1.21
- Modpack Link: [Craftoria](https://legacy.curseforge.com/minecraft/modpacks/craftoria/files/5505036)

**Comment by SSKirillSS** [comment] 2024-07-14 17:02
That's weird a bit, since I can't reproduce this issue on a pure installation of Relics. It may be a result of upgrading Relics version on already existed world. And if it's true, this issue shouldn't happen with a newly created Ender Hand (for example, you may try to take one from creative).

We will try to research this issue more, let us know if you'll find something

**Comment by SSKirillSS** [comment] 2024-07-16 19:20
Should be fixed now.

**Closed as completed by SSKirillSS** 2024-07-16 19:20 UTC
